   ! NOTE: This source file contains an example PitchCntrl() user-specified
   !       routine for computing blade pitch control commands based on transfer
   !       function descriptions specified in a pitch.ipt input file.  This
   !       routine was written by Craig Hansen (ACH) of Windward Engineering
   !       LLC.  Questions related to the use of this routine should be
   !       addressed to Craig Hansen.
module PitchCntrl_ACH
contains
!=======================================================================
SUBROUTINE PitchCntrlSinusoidal (t, P0, A, omega, Phi, BlPitch, ElecPwr, LSS_Spd, TwrAccel, NB, ZTime, DT, DirRoot, BlPitchCom )
USE                            NWTC_Library
IMPLICIT                        NONE
INTEGER   , INTENT(IN )      :: NB                                              ! Number of blades.
REAL(DbKi),                     INTENT(IN   )  :: t           !< Current simulation time in seconds
Real(ReKi),                     INTENT(IN   )  :: P0  
Real(ReKi),                     INTENT(IN   )  :: A  
Real(ReKi),                     INTENT(IN   )  :: omega
Real(ReKi),                     INTENT(IN   )  :: Phi  
REAL(ReKi), INTENT(IN )      :: BlPitch (NB)                                    ! Current values of the blade pitch angles (rad)
REAL(DbKi), INTENT(IN )      :: DT                                              ! Integration time step (sec)
REAL(ReKi), INTENT(IN )      :: ElecPwr                                         ! Electrical power (watts)
REAL(ReKi), INTENT(IN )      :: LSS_Spd                                         ! LSS speed (rad/s)
REAL(ReKi), INTENT(OUT)      :: BlPitchCom(NB)                                    ! Desired pitch angles returned by this subroutine (rad)
REAL(ReKi), INTENT(IN )      :: TwrAccel                                        ! Tower top acceleration (m/s^2)
REAL(DbKi), INTENT(IN )      :: ZTime                                           ! Current simulation time (sec)
CHARACTER(1024), INTENT(IN ) :: DirRoot                                         ! The name of the root file including the full path to the current working directory.  This may be useful if you want this routine to write a permanent record of what it does to be stored with the simulation results: the results should be stored in a file whose name (including path) is generated by appending any suitable extension to DirRoot.

BlPitchCom(:) = P0+A*sin(omega*t+Phi)

RETURN
END SUBROUTINE PitchCntrlSinusoidal

!=======================================================================
SUBROUTINE PitchCntrlStep (t, P0, A, t1, t2, BlPitch, ElecPwr, LSS_Spd, TwrAccel, NB, ZTime, DT, DirRoot, BlPitchCom )
USE                            NWTC_Library
IMPLICIT                        NONE
INTEGER   , INTENT(IN )      :: NB                                              ! Number of blades.
REAL(DbKi),                     INTENT(IN   )  :: t           !< Current simulation time in seconds
Real(ReKi),                     INTENT(IN   )  :: P0  
Real(ReKi),                     INTENT(IN   )  :: A  
Real(ReKi),                     INTENT(IN   )  :: t1
Real(ReKi),                     INTENT(IN   )  :: t2  
REAL(ReKi), INTENT(IN )      :: BlPitch (NB)                                    ! Current values of the blade pitch angles (rad)
REAL(DbKi), INTENT(IN )      :: DT                                              ! Integration time step (sec)
REAL(ReKi), INTENT(IN )      :: ElecPwr                                         ! Electrical power (watts)
REAL(ReKi), INTENT(IN )      :: LSS_Spd                                         ! LSS speed (rad/s)
REAL(ReKi), INTENT(OUT)      :: BlPitchCom(NB)                                    ! Desired pitch angles returned by this subroutine (rad)
REAL(ReKi), INTENT(IN )      :: TwrAccel                                        ! Tower top acceleration (m/s^2)
REAL(DbKi), INTENT(IN )      :: ZTime                                           ! Current simulation time (sec)
CHARACTER(1024), INTENT(IN ) :: DirRoot                                         ! The name of the root file including the full path to the current working directory.  This may be useful if you want this routine to write a permanent record of what it does to be stored with the simulation results: the results should be stored in a file whose name (including path) is generated by appending any suitable extension to DirRoot.

if (t<t1) then
   BlPitchCom(:) = P0
else if (t<t2) then
   BlPitchCom(:) = P0 + A
else 
   BlPitchCom(:) = P0
endif

RETURN
END SUBROUTINE PitchCntrlStep


end module PitchCntrl_ACH
   
