name: 'Compile OpenFAST'
description: 'Compile part or all of OpenFAST'
author: 'Rafael Mudafort https://github.com/rafmudaf'

# inputs:
#   build-type:
#     description: 'Set the CMake build type: Release (-O3); RelWithDebInfo (-O2 -g); Debug (-g)'
#     default: 'Release'
#   build-targets:
#     description: 'Which targets to compile'
#     default: 'install'

runs:
  using: 'composite'
  steps:
  # - name: Get latest CMake
  #   uses: lukka/get-cmake@v3.17.3
  - name: Build OpenFAST executable
    uses: lukka/run-cmake@v2.5
    with:
      cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
      cmakeBuildType: RelWithDebInfo
      cmakeGenerator: UnixMakefiles # default is Ninja - Ninja 1.10 doesnt support Fortran
      cmakeAppendedArgs: -DBUILD_TESTING=ON
      buildDirectory: "${{ github.workspace }}/build"
      buildWithCMakeArgs: "--target install"
  # - name: 'Run NWTC tests'
  #   uses: ./.github/actions/tests-module-nwtclibrary
  # - name: 'Run AeroDyn tests'
  #   uses: ./.github/actions/tests-module-aerodyn    
  # - name: 'Run BeamDyn tests'
  #   if: contains( github.event.pull_request.labels.*.name, 'Action Test All')
  #   uses: ./.github/actions/tests-module-beamdyn
