  
name: 'Development Pipeline'

on:
  push:

  pull_request:
    types: [labeled] #, assigned]

# runs-on: ${{ matrix.os }}
# strategy:
#   matrix:
#     os: [macOS-10.14, ubuntu-18.04]
# runs-on: docker://rafmudaf/openfast-ubuntu:alpha

jobs:
  push-pipeline:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: recursive
      - name: 'Compile targets'
        uses: ./.github/actions/compile

  # pull-request-pipeline:
  #   if: contains( github.event.pull_request.labels.*.name, 'Action Test All')
  #   steps:
  #   - name: 'Run test suite'
  #     uses: ./.github/actions/compile-and-test
